# Site settings
title: Gymnastx asd - ginnastica ritmica, artistica, acrobatica, tessuti e cerchio aereo a Reggio Emilia
email: info@gymnastx.it
description: > # this means to ignore newlines until "baseurl:"
  Gymnastx è una associazione sportiva dilettantistica che promuove
  la ginnastica ritmica, artistica, acrobatica, tessuti e cerchio aereo
  a Reggio Emilia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gymnastx.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Data pages generator
page_gen:
  - data: corsi
    template: corso
    name: dirname
    dir: corsi
    dirs: True

host: 0.0.0.0
